### ISSUE TITLE
How to change the language?

### ISSUE THREAD

**Issue by Z-fly** [chris1111/Wireless-USB-Adapter#101]
I've seen the translation.

**Comment by chris1111** [comment]
which language want to install ?

**Comment by Z-fly** [comment]
Simplified Chinese

**Comment by chris1111** [comment]
Check if this is translate in the good language then add this on
Library/Application Support/WLAN/StatusBarApp.app/Contents/Resources

**Comment by Z-fly** [comment]
> Check if this is translate in the good language then add this on
> Library/Application Support/WLAN/StatusBarApp.app/Contents/Resources
> [zh-CN.lproj.zip](https://github.com/chris1111/Wireless-USB-Adapter/files/5626502/zh-CN.lproj.zip)
> Open the **Localizable.strings** file with Textedit

This file is **incompatible**  with Release V13.
