### ISSUE TITLE
The icon looks sus 

### ISSUE THREAD

**Issue by samrth012** [chris1111/Wireless-USB-Adapter#106]
The icon shouldn't have a white background as in attached image but the original one looks a bit different but the only difference is white outline over the icon.
{ Default icon in the package }
![Screenshot 2021-01-14 at 12 57 53 PM](https://user-images.githubusercontent.com/63335952/104557986-1f7ff880-5668-11eb-9d78-aa7fcccba871.png) 
It has a white outline kindly update it.

{ Original } 
![Screenshot 2021-01-14 at 12 58 30 PM](https://user-images.githubusercontent.com/63335952/104558048-34f52280-5668-11eb-88e9-4513738480d9.png)

**Comment by chris1111** [comment]
This is already discuss many time 😀 this is the only way to have DarkMode and LigtMode on macOS Catalina
