### ISSUE TITLE
Inaccurate WPS dialog

### ISSUE THREAD

**Issue by cortig** [chris1111/Wireless-USB-Adapter#107]
Whenever I connect to an open WiFi and the signal gets weak and I get disconnected, I get a WPS prompt asking me to enter a PIN in the WPS AP configuration page even though the AP doesn’t even offer WPS.

![Screen Shot 2021-01-15 at 18 56 50](https://user-images.githubusercontent.com/4331882/105362967-84d46c00-5bc9-11eb-9bba-adc3587993e2.png)

There shouldn’t be any prompt and the adapter  should simply attempt to reconnect.

**Comment by chris1111** [comment]
Problem is from the Realtek developer
please contact Realtek

**Comment by cortig** [comment]
Already done! Thanks.
