### ISSUE TITLE
RTL8188S

### ISSUE THREAD

**Issue by chromer030** [chris1111/Wireless-USB-Adapter#11]
Hi @chris1111 , Thanks for your great work.
Please add support for RTL8188S
(Prolink wn2001)
Product ID : 0x8188
Vendor ID : 0x07b8
By Installing RTL8192SU8.kext , Dongle is recognized and present in System Preferences/Network , but noting on Statusbarapp.app ( No USB wifi Plug in ).
I tried copying device and vendor id from RTL8192SU8.kext to rtwlanu1827.kext , this time adaptor recognized by Statusbarapp.app but no network found.

**Comment by chris1111** [comment]
> Hi @chris1111 , Thanks for your great work.
> Please add support for RTL8188S
> (Prolink wn2001)
> Product ID : 0x8188
> Vendor ID : 0x07b8
> By Installing RTL8192SU8.kext , Dongle is recognized and present in System Preferences/Network , but noting on Statusbarapp.app ( No USB wifi Plug in ).
> I tried copying device and vendor id from RTL8192SU8.kext to rtwlanu1827.kext , this time adaptor recognized by Statusbarapp.app but no network found.

Please don't post Issue for an Incompatible drivers for this utility! Thats nothing to do with this
Issue closed and will be deleted
