### ISSUE TITLE
Add "Open Network Preferences"

### ISSUE THREAD

**Issue by f4810** [chris1111/Wireless-USB-Adapter#110]
Hi, this driver is great. 
Why don't You add a link to "Open Network Preferences" ? 
It's a useful shortcut that's in the original wifi icon. I'm actually leaving up the original icon only for this link...

Anyway, a great work.

![Schermata 2021-01-30 alle 11 02 18](https://user-images.githubusercontent.com/13132588/106353565-cbbe1200-62eb-11eb-935e-2573d3a1f2c4.png)

**Comment by chris1111** [comment]
yea good idea I don't know why Realtek never thinking to this?
