### ISSUE TITLE
Can someone make it work for M1?

### ISSUE THREAD

**Issue by datnvh** [chris1111/Wireless-USB-Adapter#122]
I understood this project are meant to support for **Hackintosh**.
But I have a different usage on a Mac. 
I use Wireless Usb Adapter to get internet wifi signal.
Then use Internet Sharing to bridge into built-in wifi card. So that I have a fast local WLAN.
I use local WLAN for file transfer, wireless deduging, etc...

As tested local WLAN speed even **faster** than cable connection speed. (~45mb/s wireless vs ~30mb/s wired).
And the speed is always stable.

Now I have an Intel Mac. 
In the future, I plan to have a M1 mac. 
I wish I could keep the usage .
It would be very nice if someone can make it work for M1

To chris1111, I have read your comment that you are only a packager.
https://github.com/chris1111/Wireless-USB-Adapter/issues/102#issuecomment-902642442
Can I just leave an issue here to looking for help from someone ?

**Comment by chris1111** [comment]
The project is not only for Hackintosh Read here
https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter

And No its not working at all for M1 chip
Sorry but you can't open an issue way out for the future
issue closed
