### ISSUE TITLE
File missing 

### ISSUE THREAD

**Issue by Greatisgreat** [chris1111/Wireless-USB-Adapter#125]
The only pkg file i can find is WIFI Icon Collor.pkg and I cant find the Wireless USB Adapter.pkg
Is the WIFI Icon Collor.pkg supposed to install the wireless adapter? If so I am getting "The Installation Failed"

Sorry if i am being stupid

**Comment by chris1111** [comment]
Link is here [Wireless USB Adapter.pkg](https://github.com/chris1111/Wireless-USB-Adapter/releases/tag/V14)

**Comment by Greatisgreat** [comment]
So is WIFI Icon Collor.pkg the pkg used to install the utility?

**Comment by chris1111** [comment]
> So is WIFI Icon Collor.pkg the pkg used to install the utility?



> Link is here [Wireless USB Adapter.pkg](https://github.com/chris1111/Wireless-USB-Adapter/releases/tag/V14)


Link is here Wireless USB Adapter.pkg
