### ISSUE TITLE
Catalina 10.15.7 Alfa AWUS036H

### ISSUE THREAD

**Issue by Bahir** [chris1111/Wireless-USB-Adapter#132]
Does not work.

![Screen Shot 2022-04-20 at 0 04 44](https://user-images.githubusercontent.com/1221047/164097206-59a4b870-57d7-436d-b775-f14e1e4d7399.png)
![Screen Shot 2022-04-20 at 0 04 19](https://user-images.githubusercontent.com/1221047/164097357-66326c8c-f29a-4074-ada5-31f423ffe7f8.png)

**Comment by chris1111** [comment]
Not support only in 10.6
