### ISSUE TITLE
8188cu doesn't work on macos12.5

### ISSUE THREAD

**Issue by zx0922** [chris1111/Wireless-USB-Adapter#134]
No usb-wifi plug in

**Comment by chris1111** [comment]
what is the brand of the adapter?

**Comment by zx0922** [comment]
MERCURY MW150UH

**Comment by zx0922** [comment]
> what is the brand of the adapter?

MERCURY MW150UH

**Comment by chris1111** [comment]
MERCURY MW150UH is only work on Windows see Support downloads
https://www.mercusys.com/en/download/mw300uh#Software

**Comment by zx0922** [comment]
> MERCURY MW150UH is only work on Windows see Support downloads https://www.mercusys.com/en/download/mw300uh#Software

Thanks for replay.
The link is mw300uh, mine is MW150UH, the chip is rtl 8188gu.

**Comment by chris1111** [comment]
No the link is MERCURY MW150UH

see https://www.mercusys.com/en/product/details/mw300uh/

Click support then Software

**Comment by zx0922** [comment]
> No the link is MERCURY MW150UH
> 
> see https://www.mercusys.com/en/product/details/mw300uh/
> 
> Click support then Software

![](https://s3.bmp.ovh/imgs/2022/08/12/49c93dfa546bdf04.png)

**Comment by chris1111** [comment]
Its for Windows

**Comment by zx0922** [comment]
> Its for Windows

yes. I mean it's MW300UH. MW150UH 's chip is rtl8188eu.
MW150UH is like this: ![](https://s3.bmp.ovh/imgs/2022/08/12/25e483a154b68582.png)

**Comment by zx0922** [comment]
it's works on macos 10.15. Is it possible work on 12.5? Thanks a lot!

**Comment by chris1111** [comment]
macOS 12 and 13 its here
https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter
Try maybe?

**Comment by zx0922** [comment]
> 

I've try. No usb-wifi plug in

**Comment by zx0922** [comment]
> macOS 12 and 13 its here https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter Try maybe?

I've try. No usb-wifi plug in
