### ISSUE TITLE
iCloud won't synchronise when connected with usb-wifi-dongle

### ISSUE THREAD

**Issue by philthepill** [chris1111/Wireless-USB-Adapter#137]
Hi

Thanks a lot for the effort to keep the drivers alive. It works like a charm. I just have a little problem with iCloud Sync.

I use the driver-installer that is for use with opencore patcher on a mid-2012 MacBook Pro on Monterey 12.4 (it's actually the driver-pack for hackintosh, but the other one did not work).

Here's my issue:
When I'm connected to internet via the external wifi-dongle, iCloud won't auto-sync. I can download folders manually from iCloud by clicking on the cloud with the downward-arrow, but the auto-sync of, say, the desktop wont work.

Now the integrated wifi of the Macbook sometimes work sometimes not. So when syncing the desktop over the external usb-dongle doesn't work, I get lucky sometimes and when turning on the onboard-wifi it will work and connect to the internet. Then I will turn off the dongle and all of a sudden iCloud auto-sync will work again.

Is there an easy way to fix this issue? I think I just need to know if there's a setting-option which will tell the iCloud to auto-sync via the usb-dongle as well.

Maybe you have an idea? If not, I'll just go to the shop and have them repair my internal wi-fi thingy.

Thanks a lot.

Kind regards,

Philipp

**Comment by chris1111** [comment]
Icloud work only with the native wifi Broadcom
