### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by blksith0** [chris1111/Wireless-USB-Adapter#140]
We're lacking uninstallation instructions.

**Comment by chris1111** [comment]
> We're lacking uninstallation instructions.

Same place as install

**Comment by blksith0** [comment]
Ctrl+F, search "uninstall" --> 0 results.
*gasp*

**Comment by blksith0** [comment]
"Each .pkg file generally differ in where they install the files, so unlike a .app bundle, there is no generalized way to uninstall the contents of a .pkg file.

A .pkg file is an installer package. It is run with the help of the macOS built-in [Installer](https://en.wikipedia.org/wiki/Installer_(macOS)) app, and allows the installation of the files contained under the package under various directories as programmed by the developer of the software."

But here's something that might help to uninstall chris1111's drivers: https://www.corecode.io/uninstallpkg/
