### ISSUE TITLE
What driver(s) does this contain?  Which Realtek chips does it support?

### ISSUE THREAD

**Issue by steveisakson** [chris1111/Wireless-USB-Adapter#141]
Knowing these would be very helpful for everyone who has products that are not on the list in Readme.md. Realtek do not make this information easily available so it is very hard to find anywhere. Thanks!

**Comment by chris1111** [comment]
Support chip is in the support list and 
the Drivers is :
RtWlanU.kext V-1830.32.b17.03122020
RtWlanU1827.kext V-827.4.b36.06122019
