### ISSUE TITLE
AWUS036ACHM

### ISSUE THREAD

**Issue by ebcoelho** [chris1111/Wireless-USB-Adapter#143]
Hello,

Is it possible to add Alfa AWUS036ACHM support for this package? On Alfa Downloads page I can see only up to Mojave but I'm using MacOS Catalina 10.15.7. 

https://files.alfa.com.tw/?dir=%5B1%5D%20WiFi%20USB%20adapter/AWUS036ACHM/MAC%20OS

Using the version V15  my 802.11n dongle TL-WN8200ND is working fine but my dongle 802.11ac Alfa AWUS036ACHM is not being recognised.

Thanks

**Comment by chris1111** [comment]
AWUS036ACHM use Mediatek Driver so go here [D-LinkUtility-Package](https://github.com/chris1111/D-LinkUtility-Package)
