### ISSUE TITLE
How to make StatusBarApp.app turned on by default?

### ISSUE THREAD

**Issue by steamu93** [chris1111/Wireless-USB-Adapter#15]
Hi
I've added the app to login items (macOS 10.12.6) and everything's fine but the app is "**off**" by default and every time I have to click on the icon and turn it on. Possible to change something in info.plist or even somewhere else to make the app "**on**" by default?

Thanks for the great work.

**Comment by chris1111** [comment]
StatusBarApp is suppose to be on by Default when its Connect 
Maybe your macOS Version is to OLD 😄I know its work for old version of macOS but its update for 
Mojave 10.14.6 and support Catalina
