### ISSUE TITLE
No USB-Wifi plug found Catelina Beta 8(19A558d)

### ISSUE THREAD

**Issue by LMoesman1998** [chris1111/Wireless-USB-Adapter#16]
After Installing the package and after a reboot, my USB adapter is not found. Installer runs without errors, but it appears the kext files are nowhere to be found. The adapter is a Alfa AWUS1900 and the company claims it worked on beta 2 with this package.

**Comment by chris1111** [comment]
Make sure the SIP security is desactivate I test on Beta 8 and its work
