### ISSUE TITLE
Need WN722N v3 newer Driver

### ISSUE THREAD

**Issue by festo95** [chris1111/Wireless-USB-Adapter#18]
Hi, I'm experiencing the same issue I had with "TL-WN722N(EU)_V3_180807_Mac", it doesn't connect to a certain network (the one in my university), which I solved with the new "TL-WN722N(UN)_V3_190906_Mac 10.14" so I ask you if you could update it.
Anyway thank you for your work, that right now is the only way to use the internet on Catalina for me

**Comment by chris1111** [comment]
> Hi, I'm experiencing the same issue I had with "TL-WN722N(EU)_V3_180807_Mac", it doesn't connect to a certain network (the one in my university), which I solved with the new "TL-WN722N(UN)_V3_190906_Mac 10.14" so I ask you if you could update it.
> Anyway thank you for your work, that right now is the only way to use the internet on Catalina for me

try an older Release
