### ISSUE TITLE
'This package is incompatible with this version of macOS' (Catalina)

### ISSUE THREAD

**Issue by PeteWilliams** [chris1111/Wireless-USB-Adapter#19]
Hi,

Your documentation says your drivers work with OSX Catalina, however when trying to install them I get an error saying 'This package is incompatible with this version of macOS'. 

The installer then aborts.

**Comment by chris1111** [comment]
> Hi,
> 
> Your documentation says your drivers work with OSX Catalina, however when trying to install them I get an error saying 'This package is incompatible with this version of macOS'.
> 
> The installer then aborts.

Did you see a package that not say This package is incompatible with this version of macOS
on MacOS Catalina

The package works well issue is on your side

**Comment by PeteWilliams** [comment]
> Did you see a package that not say This package is incompatible with this version of macOS
> on MacOS Catalina

I'm not sure what you mean. Could you clarify please?

**Comment by chris1111** [comment]
> > Did you see a package that not say This package is incompatible with this version of macOS
> > on MacOS Catalina
> 
> I'm not sure what you mean. Could you clarify please?

I mean that all the packages have the same warning in macOS Catalina because the disk is read-only unless you set it to read

What kind of mac Do you have to use a USB key? it must be an old mac ?

I Will show you a video on real mac book pro 13P Retina late 2013

**Comment by PeteWilliams** [comment]
My apologies - I made a mistake. I mixed up two packages that I have downloaded. This one works fine and I have it working now, thanks.

**Comment by chris1111** [comment]
> My apologies - I made a mistake. I mixed up two packages that I have downloaded. This one works fine and I have it working now, thanks.

No problem I understand 😄
 I have edit the post with a video on MacOS Catalina from my MacBook Pro
