### ISSUE TITLE
Not an issue rather suggestion

### ISSUE THREAD

**Issue by astronyu** [chris1111/Wireless-USB-Adapter#21]
This works wonders with EDUP EP-AC1619. Just a suggestion or I think more appropriately called a request, can it have a detailed info when clicked with option key? For an instance, holding option key and clicking wifi statusbar will show you detail info of the speed you're using etc.

Other than that, great work! Installed this on macos catalina 10.15 on a macbook pro 13 early 2011.

**Comment by chris1111** [comment]
> This works wonders with EDUP EP-AC1619. Just a suggestion or I think more appropriately called a request, can it have a detailed info when clicked with option key? For an instance, holding option key and clicking wifi statusbar will show you detail info of the speed you're using etc.
> 
> Other than that, great work! Installed this on macos catalina 10.15 on a macbook pro 13 early 2011.

I am not the developper of the app but nice request thanks
