### ISSUE TITLE
Archer T2U AC600 not working 

### ISSUE THREAD

**Issue by paulaecolina** [chris1111/Wireless-USB-Adapter#22]
Hello Chris, thanks for your hard work. 

Just wanted to ask if anyone else is having the same trouble as me, since my USB adapter version doesn’t work with the app, after several tries to install. But the app does work, since it shows up on the status bar. 

My USB adapter is a bit old but it still works, I tried another older one but it also didn’t work. Says no USB device found. 

Not sure if it’s just my laptop acting up

**Comment by chris1111** [comment]
Try a differant release with a differant drivers
