### ISSUE TITLE
WPA2 Enterprise AES not working

### ISSUE THREAD

**Issue by chr1smb** [chris1111/Wireless-USB-Adapter#27]
Hello, I am unable to connect to my college’s Wifi: AUTO(PEAP), WPA2 Enterprise AES password. However, I am able to connect to my home wifi and my iPhone Personal Hotspot.

Wifi Device: Edimax EW-7822ULC
Wireless USB Adapter.pkg version: V7 
Device: MacBook Pro 2011,  macOS 10.15.1

**Comment by chris1111** [comment]
See here
https://github.com/chris1111/Wireless-USB-Adapter/issues/1
