### ISSUE TITLE
Unable to connect using WiFi Adapter in Mac OS 10.15.1

### ISSUE THREAD

**Issue by sankarsv** [chris1111/Wireless-USB-Adapter#28]
I bought TL-WN725N (Ver 3.0)(chipset: Realtek RTL8188EUS). The official driver for MacOS 10.15.1 hasn't been released by tp link. So I tried using your driver as suggested in tp link community site. I disabled sip, installed the pkg and restarted the machine..I had the usb connected. USB Wireless icon is visible but it shows 'No USB WiFi Plugin'. Kindly help..
PS: Thumbs up for the wonderful work you are doing.

**Comment by chris1111** [comment]
Not really the good choice you have done, your USB Utility works on Linux only, no Drivers for macOS 
![Capture d’écran, le 2019-11-17 à 08 55 27](https://user-images.githubusercontent.com/6248794/69008413-42a20180-0918-11ea-98dc-91a7e8973822.png)
 See https://www.tp-link.com/fr-ca/support/download/tl-wn725n/
