### ISSUE TITLE
Edimax EW-7822ULC tested and working

### ISSUE THREAD

**Issue by philip-lamb** [chris1111/Wireless-USB-Adapter#29]
You might wish to note in your README that this works well with the Edimax EW-7822ULC USB wifi adapter (https://www.edimax.com/edimax/merchandise/merchandise_detail/data/edimax/global/wireless_adapters_ac1200_dual-band/ew-7822ulc/)

**Comment by chris1111** [comment]
Thanks for sharing, you have tested in Catalina 10.15 or Mojave ?
The adapter is already in the **View List**
Thanks anyway

![Capture d’écran, le 2019-11-18 à 05 20 31](https://user-images.githubusercontent.com/6248794/69044657-49d21980-09c3-11ea-9ab1-7e93d365fc8c.png)
