### ISSUE TITLE
Very slow speed

### ISSUE THREAD

**Issue by kilgil27** [chris1111/Wireless-USB-Adapter#30]
I have the edimax EW-7822ULC. Running Catalina. I am able to install the driver and connect to my network, but the speed is painfully slow. It's basically unusable. speedtest is showing 20-30 kb/s. Tried on two different wifi networks. Speeds are all excellent when using the dongle within Windows 10. Any ideas what the issue may be?

**Comment by chris1111** [comment]
No Idea, just wait for the new release driver soon
