### ISSUE TITLE
Problem with TL-WN725N (Ver 3.0) on Mojave

### ISSUE THREAD

**Issue by elrafita** [chris1111/Wireless-USB-Adapter#31]
Hi i just read this its not the best adapter, i have a problem, when i start the sistem adapter connects and in 30 sec desconects and last like 1 min to connect again, and then it loses the connection from time to time and comes back by itself(looks all the time connected but internet doesnt work) also ip settings are ok when internet doesnt work.

Ty

**Comment by chris1111** [comment]
with which release?

**Comment by elrafita** [comment]
i use mojave 10.14.6 but i confused place to write it i use for this adapter USB.Wireless.Utility.dmg, also tryed thisone, but doesnt detect the adapter, only works with the utility
