### ISSUE TITLE
Problems with Archer T3U

### ISSUE THREAD

**Issue by VictorCandido** [chris1111/Wireless-USB-Adapter#33]
Hi, I'm having some problems with my wifi adapter and its drivers. I tried to install the last version of the drivers just like it is showed in the video, but it didn't worked to me. My Mac still not recognizing the Tp-Link adapter. What should I do?

I've installed the V8 driver and reboot my system. I've already changed the USB port, connected and disconnected many times... But it is still not working.

My adapter: Tp-Link Acher T3U
My SO: Mac OS 10.15.2 Catalina
My Macbook: MacBook Air (Early 2014)

Can anyone help, please? I really need to have my Wifi working as soon as possible.

Thanks.

**Comment by chris1111** [comment]
Uninstall and try the V7 Release

**Comment by VictorCandido** [comment]
I have installed and uninstalled all the versions, but nothing happened.... Still not working :/

**Comment by chris1111** [comment]
Dont know what's wrong with the Tp-Link Acher T3U
