### ISSUE TITLE
[Not an issue] Verified compatibility with Realtek 8812BU on macOS Catalina

### ISSUE THREAD

**Issue by Raizelian** [chris1111/Wireless-USB-Adapter#35]
This is not an issue, rather a notice: I verified on my Mac running macOS 10.15.2 Catalina that this package is working perfectly with a Wi-Fi USB (802.11ac) adapter with a Realtek 8812BU chipset.
It's working with internet sharing, too, both in 2.4 and 5 GHz.
The drivers included with my adapter weren't updated to work with Catalina, but these work amazingly, so thank you!

**Comment by chris1111** [comment]
what is your adapter ?

**Comment by deweydb** [comment]
Strange, we I have a device with this chipset and it is reporting as "no usb wifi plugged in"
