### ISSUE TITLE
RTL8188EUS Support

### ISSUE THREAD

**Issue by ann0see** [chris1111/Wireless-USB-Adapter#37]
I just connected a LogiLink WL0145A and it seems to get recognised (en3 in network preferences). But there is no connection possible. Are there plans to support this chip?

**Comment by chris1111** [comment]
WL0145A is support by the program

**Comment by ann0see** [comment]
Just the Blue LED didn’t blink. That was the problem.

**Comment by chris1111** [comment]
Uninstall the programm, reboot and try release V7 Please
thanks let me known

**Comment by chris1111** [comment]
Ok I just check the driver for your utility and its not the same
sorry my bad
![Capture d’écran, le 2019-12-30 à 19 36 36](https://user-images.githubusercontent.com/6248794/71606048-c7995100-2b3b-11ea-8650-ce3a52b2ee4e.png)

**Comment by ann0see** [comment]
The latest version does work. I‘m sorry for opening the issue. Probably it was due to an other WiFi dongle which was still plugged in.
