### ISSUE TITLE
DWA-131 MacOS Catalina Slow speeds

### ISSUE THREAD

**Issue by ucristian3** [chris1111/Wireless-USB-Adapter#38]
I know that there is no official drivers for catalina yet,and I tried yours ...
everithing work good but de download/browsing speeds are very slow.

**Comment by chris1111** [comment]
Try release V7 
let me know

**Comment by ucristian3** [comment]
yeah.  V7 somehow fixed the issue...you are the man,thanks!

**Comment by chris1111** [comment]
> yeah. V7 somehow fixed the issue...you are the man,thanks!

Great 😁
