### ISSUE TITLE
Can‘t use WPA2 Enterprise AES network on my mac 10.15.2

### ISSUE THREAD

**Issue by caohrong** [chris1111/Wireless-USB-Adapter#39]
I use iMac 27-inch. But I can't use WPA2 Enterprise AES this kind of Wifi on my mac. It seems trying to connect the wifi again and again. other wifi working properly(like WPA2 Personal). Anyone know about it? Thanks.

system: 10.15.2
driver version: v1830.32.b13.11052019
usb wifi type: CF-WU810N

**Comment by chris1111** [comment]
See here
https://github.com/chris1111/Wireless-USB-Adapter/issues/1
