### ISSUE TITLE
System Extension blocked in release V8 in catalina 10.15.2

### ISSUE THREAD

**Issue by heng950620** [chris1111/Wireless-USB-Adapter#40]
Hi. i have the issue with System Extension blocked in release V8 on my recently MacOS catalina 10.15.2
my WIFI stick is using TP-Link Archer T3U mini 1300Mbps.

have tried V7 release but when i connect to my network it freeze while when i only plug in and no connect internet its run fine on my system.
* i already try with SIP enable and gatekeeper disable its still the same issues

**Comment by chris1111** [comment]
> Hi. i have the issue with System Extension blocked in release V8 on my recently MacOS catalina 10.15.2

> * i already try with SIP enable and gatekeeper disable its still the same issues

You have to try SIP Disable not enable
