### ISSUE TITLE
[Not an issue] Handoff, watch unlock

### ISSUE THREAD

**Issue by calibrae** [chris1111/Wireless-USB-Adapter#41]
Hi,
Is there any way to enable apple watch unlock with this driver?
![image](https://user-images.githubusercontent.com/1745159/74323230-81afe980-4d85-11ea-8ee4-3cbcf2c82393.png)

Thanks !

**Comment by chris1111** [comment]
For now I don't think so ?
You can post to the forum of the constructer of the USB (Exe: TP Link)
if you have an answer please tell us
Thank you
