### ISSUE TITLE
Mac Won't boot after install

### ISSUE THREAD

**Issue by moatazhamada** [chris1111/Wireless-USB-Adapter#43]
Mac Catalina 10.15.3 (Hackintosh) after installing the v8 it asked for restart and didn't boot after that and takes forever to load and wont start at the end either

**Comment by chris1111** [comment]
Works good here! this is strange ??

**Comment by moatazhamada** [comment]
can you help me with that ? i can access the mac files from dual boot i even deleted the files was installed by the app but it still wont boot

**Comment by chris1111** [comment]
The programme is not responsable of an unbootable macOS
Its not on the cause sorry but find your issue, How can I help you ?

**Comment by moatazhamada** [comment]
I dont know but it really happened when the installation asked for restart

**Comment by mlostekk** [comment]
Same here. I have forgot to disable `SIP`. Now my mac does not boot anymore. Any tips?

**Comment by mlostekk** [comment]
I am on mojave by the way

**Comment by chris1111** [comment]
> I am on mojave by the way

Boot in recovery HD 
Open terminal type
csrutil disable

Then reboot maybe works

**Comment by mlostekk** [comment]
Well, it was disabled when i installed your tool. 

And tried that to boot with disabled mode. Unfortunately it does not work.

**Comment by mlostekk** [comment]
Any other idea except recovering from a backup?

**Comment by chris1111** [comment]
Reinstall a good macOS because this is already test with a  successful result including me on my MacBook Pro
 I receive a hundred mail by month 
Your Mac run with an issue

**Comment by pppaolo** [comment]
I installed it with crsutil enabled apparently. Now it doesnt boot, it get stuck at login bar. Tried any possible safe mood booting.
I also went to recovery mode, terminal and typed csrutil disable. 
Please help.

**Comment by chris1111** [comment]
> I installed it with crsutil enabled apparently. Now it doesnt boot, it get stuck at login bar. Tried any possible safe mood booting.
> I also went to recovery mode, terminal and typed csrutil disable.
> Please help.

I have SIP Enable on my MacBook Pro late 2013 and I never have any issue to reboot
No one is responsabble for your MacBook

**Comment by pppaolo** [comment]
Thanks for responding so quickly!
I have a macbook pro 2018 I believe.
Never had an issue before.
I installed the wireless usb driver, last version from your github without
disabling SIP.
Restarted the mac and its stuck at 100% loading bar.

What do you suggest I do?
