### ISSUE TITLE
some contribution

### ISSUE THREAD

**Issue by Airomeo** [chris1111/Wireless-USB-Adapter#44]
hi

here is some resources for you.Including some icons and language translation
Realtek WirelessUtility Translation(Simplified Chinese)
dark and light and other icons 

[https://drive.google.com/open?id=1YS4PWLW0R09enLngL4Mxp-Kjcr369VMc](url)

thanks

**Comment by chris1111** [comment]
> hi
> 
> here is some resources for you.Including some icons and language translation
> Realtek WirelessUtility Translation(Simplified Chinese)
> dark and light and other icons
> 
> [https://drive.google.com/open?id=1YS4PWLW0R09enLngL4Mxp-Kjcr369VMc](url)
> 
> thanks

Your link not work

**Comment by chris1111** [comment]
thanks I will add to the app

**Comment by chris1111** [comment]
edit ********

Release V9 IS remove  because bug report here
https://github.com/chris1111/Wireless-USB-Adapter/issues/45

**Comment by Airomeo** [comment]
Sorry for the wrong release.

There is no need to put InfoPlist.strings and MainMenu.nib into the zh-Hans.lproj. Now I have removed.
And here is the updated translation localizable file. It works well in my Mac OS 10.15.3.

![截屏2020-02-2117 46 30](https://user-images.githubusercontent.com/24858725/75023617-15469000-54d3-11ea-898a-848e49a18cfe.png)

**Comment by chris1111** [comment]
I have Add your translation to the front page
[[zh-Hans for Wireless Utility](https://www.notion.so/zh-Hans-for-Wireless-Utility-a31dd055f5be4db4ae6be58f36559bc2)]([zh-Hans for Wireless Utility](https://www.notion.so/zh-Hans-for-Wireless-Utility-a31dd055f5be4db4ae6be58f36559bc2))

**Comment by Airomeo** [comment]
Oh bro, you are very welcome. 
You can add it to the next release after your test. Just copy it and paste to StatusBarApp.app/Contents/Resources/zh-Hans.lproj/Localizable.strings. that's all.

Thank you very much.

**Comment by seekhust** [comment]
Hi,
I have installed the wireless USB adapter V11 for catalina 10.15.2.

I found it's interesting.

I can see the hardware of the USB wifi under the system report-hardware-USB device tree.

But The USB WIFI adapter can't be recognized on the tool bar. When I click the wifi icon, it say "No USB-WIFI Plug in"

How it happened?

THanks.

**Comment by seekhust** [comment]
Hi,
I have installed the wireless USB adapter V11 for catalina 10.15.2.

I found it's interesting.

I can see the hardware of the USB wifi under the system report-hardware-USB device tree.

But The USB WIFI adapter can't be recognized on the tool bar. When I click the wifi icon, it say "No USB-WIFI Plug in"

How it happened?

THanks.
