### ISSUE TITLE
[Bug] Wireless USB Adapter-V9 && Clover-V12

### ISSUE THREAD

**Issue by HsOjo** [chris1111/Wireless-USB-Adapter#45]
* When I use this driver V8, it works normally. (on 10.15.3)

However, when updating to V9 or clover V12, the following occurs.
![Error](https://user-images.githubusercontent.com/28259134/74971874-be51a400-545b-11ea-85f2-fd9acdab6842.png)

After that, I try to find the exception; When I compare files, I found the problem.

* /Library/Application Support/WLAN/StatusBarApp.app/Contents/Resources/zh-CN.lproj/InfoPlist.strings

```
/* Localized versions of Info.plist keys */

VersionString= "5.0.7 (2018/02/23)";

DriverName = "All"; /Library/Application Support/WLAN/StatusBarApp.app/Contents/Resources/zh-CN.lproj/Localizable.strings
```

When I delete this file, It works normally again.

**Comment by HsOjo** [comment]
There is another problem. When I upgrade my system to 10.15, ISTAT menus cannot monitor the download traffic of the device.

* This is true for all versions of the driver.

![image](https://user-images.githubusercontent.com/28259134/74973367-45078080-545e-11ea-8810-0ae2b29e9600.png)

If I use other wired external Ethernet devices, they all work well.

Maybe some interface haven't implements? ? ?

Thanks.          :)

**Comment by chris1111** [comment]
I roll back to V8 thanks
