### ISSUE TITLE
RTL8812AU doesn't work on these channel(36-140)

### ISSUE THREAD

**Issue by Airomeo** [chris1111/Wireless-USB-Adapter#49]
Hey bro. 
See you again. 
Last time i opened an [issue](https://github.com/chris1111/Wireless-USB-Adapter/issues/44#issuecomment-590001790) about the icons and translation. It works well and i thought you would add it to the next release.  But you didn't. I hope you can add it to the statusbarapp so that we don't need to add it to the folder manually. I have packed the translation file to here.https://drive.google.com/open?id=1BatGoBNV5P6PkoN7Qbt8deWUbf5yVoqo

RTL8812AU doesn't work on these channel(36-140). I've had this problem for a long time. Recently i figure out why my usb adapter can't receive my 5G wifi. I change my wireless router 5G channel to 149. Then i can reveive and it works well. I had the same problem with Windows 10, and I saw a lot of people on the Internet who had the same problem, and I was able to fix it by changing the driver of the wireless adapter. Therefore, I think it should be the same solution on the Mac OS system. Someone Shared the driver code of RTL8812AU on github, which may need to be compiled. As my level is limited, I can only help you with this. 

Thank you very much!

**Comment by chris1111** [comment]
There is no code for Realtek Driver macOS on GitHub, I never see
