### ISSUE TITLE
Generic dongle

### ISSUE THREAD

**Issue by Gab627** [chris1111/Wireless-USB-Adapter#50]
I have a Mac with Mojave, and a generic usb dongle. I checked the cd drivers that came with it, and it won't do anything. The dongle is recognized in system information, but won't show on network settings.
It seems that is a RTL8188EUS, because of what i saw on the linux drivers from the CD.
Is there any solution?
Thanks for your time

**Comment by chris1111** [comment]
Please post the package of CD Drivers here

**Comment by Gab627** [comment]
The file was too big to upload here.
https://drive.google.com/open?id=19S71bwVBJPspFfgAKzqsMfEUfIhTPNru

**Comment by chris1111** [comment]
Sorry this is not support, this driver stop working at MacOS X Lion 10.7

See driver
![Capture d’écran, le 2020-03-12 à 20 07 04](https://user-images.githubusercontent.com/6248794/76577962-5c55ee80-649d-11ea-9575-26b97efe382c.png)
