### ISSUE TITLE
Alfa AWUS036NH (Ralink RT2870 chipset) won't open in Mojave 10.14.6

### ISSUE THREAD

**Issue by ryan-mulrooney** [chris1111/Wireless-USB-Adapter#53]
Hi, I know you don't have this particular USB adapter and chipset listed as being supported.

But... Do you have a driver that will work for it? 

I've downloaded the driver from the Alfa website and it is useless. The "Wireless Utility" doesn't open... this is common issue for many people and Alfa is a popular USB adapter.

Thanks.

**Comment by chris1111** [comment]
Your in the good place 
Yes I have [USB Wireless Utility](https://github.com/chris1111/USB-Wireless-Utility)
