### ISSUE TITLE
HELP: No USB WiFi Plugin

### ISSUE THREAD

**Issue by Vanyoo** [chris1111/Wireless-USB-Adapter#54]
Hello bro, I need help...

I use hackintosh, having WN823N, and installed your latest version driver.

![image](https://user-images.githubusercontent.com/10300206/77515740-11cc6d00-6eb4-11ea-822e-9e887e65a5d7.png)
when I plug in the device, OS can detect it. But the driver cannot...

And my SIP status:
`System Integrity Protection status: unknown (Custom Configuration).

Configuration:
        Apple Internal: disabled
        Kext Signing: disabled
        Filesystem Protections: disabled
        Debugging Restrictions: disabled
        DTrace Restrictions: disabled
        NVRAM Protections: disabled
        BaseSystem Verification: disabled
`
(I using opencore as bootloader)

**Comment by Vanyoo** [comment]
![image](https://user-images.githubusercontent.com/10300206/77517256-c8c9e800-6eb6-11ea-85bd-ea312357e05b.png)

**Comment by chromer030** [comment]
As it's shown in your screenshot , your adapter is Mediatek Ralink based chipset.
This driver is for Realtek based chipsets.

**Comment by Vanyoo** [comment]
> https://github.com/chris1111/Wireless-Ralink-Panel-Utility

Thank you so much, let me try it!
