### ISSUE TITLE
Please Help Support Edimax EW-7711MAC

### ISSUE THREAD

**Issue by cricrazy** [chris1111/Wireless-USB-Adapter#57]
I have got Edimax 5Ghz mac version adapter. It is not working with Mac Catelina. I have installed the Wireless USB Adapter. But it says USB not found.

**Comment by chromer030** [comment]
This adaptor is using Ralink chipset and needs RT2870USBWirelessDriver.kext
so you should use this package :
https://github.com/chris1111/Wireless-Ralink-Panel-Utility

**Comment by cricrazy** [comment]
That worked perfectly. Thank you very much. You saved me a whole new installation. Great work.

**Comment by chris1111** [comment]
you don't have Email so I adise you here stop posting spam in [Wireless USB adapter Clover](https://github.com/chris1111/Wireless-USB-Adapter-Clover)
