### ISSUE TITLE
Open up my Mac security and install your driver?

### ISSUE THREAD

**Issue by gcallah** [chris1111/Wireless-USB-Adapter#59]
Why should anyone think this is not a backdoor?

**Comment by chromer030** [comment]
All the kexts are signed by Realtek and by modifying/renaming , adding/removing data to/from them , the signature will be lost.
And about utility , its originaly writen by Relatek , and if you dont trust this utility from this package you can use utility released by vendors like Asus , TP-link , Edimax , etc... all are same.

**Comment by chris1111** [comment]
> Why should anyone think this is not a backdoor?

Because is Parano

**Comment by chris1111** [comment]
> Why should anyone think this is not a backdoor?
Why did you say this, you did not read the guide
Here is an installation on macOS Catalina 10.15.4 with SIP activated
<img width="806" alt="Untitled" src="https://user-images.githubusercontent.com/6248794/79031584-ad750300-7b6d-11ea-9dce-fb766422319e.png">

**Comment by chris1111** [comment]
> Why should anyone think this is not a backdoor?

Why did you say this, you did not read the guide
Here is an installation on macOS Catalina 10.15.4 with SIP activated
<img width="806" alt="Untitled" src="https://user-images.githubusercontent.com/6248794/79031584-ad750300-7b6d-11ea-9dce-fb766422319e.png">
