### ISSUE TITLE
Thanks for the Driver:RTL8188CU

### ISSUE THREAD

**Issue by Raeesreyi** [chris1111/Wireless-USB-Adapter#62]
First, very thanks for providing a driver.
I had installed and all done perfect. Only one issue is really **very slow internet** and to add **I can't login to iCloud or create one.** Keeps showing me errors.
But is there a way to get rid of **100KBPS** speed trapped inside my hack. My hack is like 100 KB or nothing. Is there a fix for that. And I did update **V15** and same result. If you can help it would be appreciated.

**Comment by chris1111** [comment]
for the connection to icloud it must be done by Cable before and then it should work by Wifi
for 100kbps you have to look at the side of your router I can't do anything for that
