### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by guillerpsanchez** [chris1111/Wireless-USB-Adapter#64]
Hello i have a t2 nano

I followed all steps but seems that is not recognized i receive "no usb-wifi card connected" message, im using open core 0.5.8 and i have moved the kext to the correct folder for opencore.

Im doing anything wrong?

Thank you in advance.

Edit: im in catalina 10.15.4

**Comment by chris1111** [comment]
Your not need to move the kext its installed in /L/E and its work if your dongle wifi is support that's it

**Comment by guillerpsanchez** [comment]
The problem is that in my laptop it works but in pc it doesnt, same usb and same macos version the only difference is open core on the pc and clover on the laptop.

**Comment by chris1111** [comment]
This program as nothing to do with Bootloader
