### ISSUE TITLE
Not seeing download throughput with V12 and 10.15.3

### ISSUE THREAD

**Issue by chnbz** [chris1111/Wireless-USB-Adapter#65]
Hey,

thank you first of all for this driver! It works but what I realized is, that the tool I am using to see my network speeds doesn't work correctly. It shows the upload speeds but download is always at 0. It is the same in the activity monitor on the network tab right bottom corner (Data received/s). Any idea what could cause this?

**Comment by chris1111** [comment]
Sorry but The Utility as nothing to do with other tools
