### ISSUE TITLE
Wifi keeps freezing 5ghz 

### ISSUE THREAD

**Issue by mobiyan** [chris1111/Wireless-USB-Adapter#66]
When I test the connection with speedtest, I loose wifi during SEND at about a quarter in. I have to disable wifi and re-enable. Down Speed 500+, Up Speed 250+

Mac Pro (2019)
3.3 Ghz 12-Core
96GB RAM
Radeon Pro W5700X

Wifi device is NetGear Nighthawk AC1900 Wifi USB Adapter (A7000)
OS 10.15.5

Merci

**Comment by mobiyan** [comment]
Seems stable at 2.4Ghz with slower speed

**Comment by chris1111** [comment]
Out of curiosity on what macOS are you?

**Comment by mobiyan** [comment]
OSX 10.15.5

**Comment by mobiyan** [comment]
Can you keep it open to see what is wrong at higher speed on 5Ghz?

**Comment by chris1111** [comment]
> Can you keep it open to see what is wrong at higher speed on 5Ghz?

No problem

**Comment by 7Backwards** [comment]
Have the same problem, and with 5ghz also

**Comment by 7Backwards** [comment]
It goes hours without anything wrong happening or after 15 min i lose internet but the utility still says im connected, need to replug and plug the wifi dongle again, if i simply turn off wifi and turn on again it doesn´t work.

**Comment by chris1111** [comment]
you should know if the 5ghz worked before Catalina to know if it does not come from the last OS's ?

**Comment by 7Backwards** [comment]
I´m using mojave, was using a older driver, installed now v12 i will report if the issue keeps happening. What i can say is that i had 2.4ghz before and this never happened, now i have 5ghz and 100% isn´t the router´s fault as i tested it before with other equipments.

**Comment by 7Backwards** [comment]
And yes, it keeps happening.

**Comment by chris1111** [comment]
so maybe you have to check with the manufacturer of the USB wifi dongle if  the is a known issue ?

**Comment by mobiyan** [comment]
I have a second wifi ac1200, BrosTrend AC1200, same thing happens.

**Comment by chris1111** [comment]
I have 3 USB dongle with stable 2.4Ghz

**Comment by dukechem** [comment]
Please try disabling IPv6 with steps below and see if that helps. NOTE: keep track of original values of any settings you change so you can undo later if need be.

https://www.privateinternetaccess.com/helpdesk/kb/articles/do-i-need-to-disable-ipv6-traffic-on-my-mac-computer
You can disable IPv6 traffic using the following instructions:

Go to Apple - > System Preferences -> Network
Select the first network connection you see listed on the left-hand side, then click the Advanced button.
Go to the TCP/IP tab at the top
Beside "Configure IPv6", set it to "Link-local Only"
Click Ok to apply the change
Repeat steps 2-5 for any remaining network connections you see in your Network window.
Reboot your computer, so all changes fully take effect.

**Comment by chris1111** [comment]
> Please try disabling IPv6 with steps below and see if that helps. NOTE: keep track of original values of any settings you change so you can undo later if need be.
> 
> https://www.privateinternetaccess.com/helpdesk/kb/articles/do-i-need-to-disable-ipv6-traffic-on-my-mac-computer
> You can disable IPv6 traffic using the following instructions:
> 
> Go to Apple - > System Preferences -> Network
> Select the first network connection you see listed on the left-hand side, then click the Advanced button.
> Go to the TCP/IP tab at the top
> Beside "Configure IPv6", set it to "Link-local Only"
> Click Ok to apply the change
> Repeat steps 2-5 for any remaining network connections you see in your Network window.
> Reboot your computer, so all changes fully take effect.

Thanks Closed

**Comment by lordkev** [comment]
This did not solve the issue for me. Even with IPv6 disabled on the interface it still drops out after running iperf for <30 seconds on an 802.11ac network.

**Comment by petkoivanov** [comment]
This also did not solve the issue for me. 
Still crashes when joining 5g wifi, fine on 2.4

**Comment by petkoivanov** [comment]
I tried drivers from the manufacturer - same exact behavior. i also switch to 'link-local only' and still crashes.
may be it is not necessarily this drivers problem but may be something similar to what $lordkev was saying about USB driver ?!
Let me know if i can provide some logs to help investigate this crash. Thanks in advance.

**Comment by chris1111** [comment]
This issue is from the Drivers so you must make a problem request to the manufacturer
Issue close
