### ISSUE TITLE
Tested + Fully Working Asus Nano-10

### ISSUE THREAD

**Issue by Hexoline** [chris1111/Wireless-USB-Adapter#68]
Tested 2.4GHz only USB adapter on latest macOS 10.15.5 + .6 beta fully working whitout any drops or slowdown.
Thanks

**Comment by chris1111** [comment]
> Tested 2.4GHz only USB adapter on latest macOS 10.15.5 + .6 beta fully working whitout any drops or slowdown.
> Thanks

https://github.com/chris1111/Wireless-USB-Adapter/issues/66
