### ISSUE TITLE
Wifi status icon randomly freeze

### ISSUE THREAD

**Issue by t3s8r8** [chris1111/Wireless-USB-Adapter#69]
Hi chris, I have problem with my USB Wifi Comfast-811AC when installing lastest V12 kext of yours. More specifics:

Wifi status icon randomly freeze, I can't even choose connect or disconnect from any (or selected) network, also my system performs a little bit laggy at the same time, then. I'm running Catalina 10.15.5.

I don't know if this is a bug from kext or my USB wifi has problem ? Besides, if you have other kext versions which suite for my USB Wifi please let me know. 

Thanks a lot for your work ! Have a nice day

**Comment by chris1111** [comment]
The kext are no Bug check your system maybe you have a bug because I never see freezing some thing like that about Realtek Utility
