### ISSUE TITLE
Suddenly stopped working, need to reinstall after each reboot

### ISSUE THREAD

**Issue by virgil9306** [chris1111/Wireless-USB-Adapter#79]
On Catalina, suddenly after a reboot, the StatusBar utility says "no usb wifi plug in". Uninstall button also did not work.

So I reinstalled it. After reboot it was OK. But, after rebooting again, same error occurred.

So now after each reboot, I need to reinstall the driver....

----

Notes: 
- No software changes recently, nothing was changed.

**Comment by chris1111** [comment]
Never see this , issue is on your side man

**Comment by virgil9306** [comment]
I figured it may be. Thank you.

2020年7月31日(金) 20:15 chris1111 <notifications@github.com>:

**Comment by Yolandavdvegt** [comment]
Having the exact same problem.

@virgil9306 what did you do to solve it?

**Comment by virgil9306** [comment]
I installed a different compatible driver that I found.

2020年10月12日(月) 4:30 Yolandavdvegt <notifications@github.com>:

**Comment by virgil9306** [comment]
Let me look it up later and I can verify which one.

2020年10月12日(月) 4:30 Yolandavdvegt <notifications@github.com>:
