### ISSUE TITLE
What is that?

### ISSUE THREAD

**Issue by md-siam** [chris1111/Wireless-USB-Adapter#82]
The Wi-Fi adapter will be shown as Ethernet,  then what is that Wi-Fi connection 
![Screen Shot 2020-08-02 at 4 07 37 AM](https://user-images.githubusercontent.com/21225918/89111306-0eef1380-d476-11ea-8e72-ee6fdbf04afb.png)

**Comment by chris1111** [comment]
you don't know what is wifi connect?
Looks like you have  BS Wifi Connect
