### ISSUE TITLE
D-Link DWA-160

### ISSUE THREAD

**Issue by nighthawk469** [chris1111/Wireless-USB-Adapter#85]
Please add support for D-Link DWA-160. 
Thank you

**Comment by chris1111** [comment]
D-Link DWA-160 working with a Mediatek drivers RT2870USBWirelessDriver.kext

**Comment by nighthawk469** [comment]
I am using a DWA-160B2 but it is not being recognized by your software. I wonder what I am doing wrong.

**Comment by chris1111** [comment]
> I am using a DWA-160B2 but it is not being recognized by your software. I wonder what I am doing wrong.


what your doing wrong is using wrong software
