### ISSUE TITLE
TL-WN823Nv2 working great as well!

### ISSUE THREAD

**Issue by DVEntertainment** [chris1111/Wireless-USB-Adapter#87]
I didn't know where to put it, so i make an issue!

I measured speeds of 20 down and 40 up, but that could be due to my wifi network. I get over 1 gig on ethernet windows.

Thanx for this AWESOME app!

**Comment by chris1111** [comment]
I may have almost the same thing and I think it becomes difficult to have a good wifi speed these days with the network distributors, for my part it is [Bell Wifi](https://www.bell.ca/Bell_Internet/Products/WiFi)
