### ISSUE TITLE
The icon is too small

### ISSUE THREAD

**Issue by z1un** [chris1111/Wireless-USB-Adapter#89]
The icon is too small. I hope it can be changed a little bigger, which is consistent with the style of other icons in the system.
![image](https://user-images.githubusercontent.com/48505413/92697669-22976f00-f37e-11ea-9b24-f8f1c4c37241.png)

**Comment by chris1111** [comment]
> The icon is too small. I hope it can be changed a little bigger, which is consistent with the style of other icons in the system.
> ![image](https://user-images.githubusercontent.com/48505413/92697669-22976f00-f37e-11ea-9b24-f8f1c4c37241.png)


Make a better one then share 😁

**Comment by z1un** [comment]
Can you make a better icon update？ hahah

**Comment by chris1111** [comment]
> Can you make a better icon update？ hahah

I have already try then almost impossible, if you see the Icon its work for Light and Dark Mode and its the only way what i found to make it work

**Comment by chris1111** [comment]
try this icon, change then reboot 
[Icon.zip](https://github.com/chris1111/Wireless-USB-Adapter/files/5202865/Icon.zip)

this icon looks more bigger on Dark mode

**Comment by z1un** [comment]
thinks

**Comment by z1un** [comment]
> 试试这个图标，先更改然后重新启动
> [Icon.zip](https://github.com/chris1111/Wireless-USB-Adapter/files/5202865/Icon.zip)
> 
> 在黑暗模式下，此图标看起来更大

How should I use it?

**Comment by chris1111** [comment]
> > 试试这个图标，先更改然后重新启动
> > [Icon.zip](https://github.com/chris1111/Wireless-USB-Adapter/files/5202865/Icon.zip)
> > 在黑暗模式下，此图标看起来更大
> 
> How should I use it?


On the Root Disk ➤/Library/Application Support/WLAN/StatusBarApp.app/Contents/Resources
Copy paste Icon
this is will change the Icon then reboot

**Comment by z1un** [comment]
> > > 试试这个图标，先更改然后重新启动
> > > [Icon.zip](https://github.com/chris1111/Wireless-USB-Adapter/files/5202865/Icon.zip)
> > > 在黑暗模式下，此图标看起来更大
> > 
> > 
> > How should I use it?
> 
> On the Root Disk ➤/Library/Application Support/WLAN/StatusBarApp.app/Contents/Resources
> Copy paste Icon
> this is will change the Icon then reboot

okay thinks！
