### ISSUE TITLE
No USB WiFi Plug In

### ISSUE THREAD

**Issue by chadarutherford** [chris1111/Wireless-USB-Adapter#9]
Upon successful installation of adapter kexts, The system icon shows up but either I get the beach ball of death, or I get No USB Wifi Plug In. I have uninstalled and reinstalled several times, to no avail. Here are my specs:

MacBook Pro (Retina, 15-inch, Mid 2015)
MacOS Catalina
2.2 GHz Intel Core i7

Trying to install these drivers to enable Wifi Bridge on VirtualBox to do wifi attacks for Ethical Hacking Course.

**Comment by chris1111** [comment]
What is your USB adapter
