### ISSUE TITLE
TL-WN722N On OS 10.15.6 Macbook Pro 2017

### ISSUE THREAD

**Issue by jtreg** [chris1111/Wireless-USB-Adapter#90]
Hi Chris, I followed the instructions to use my TP-LINK TL-WN722N on Macbook Pro 2017 with OS 10.15.6 Catalina. After reboot the 802.11 did not appear in list of devices in System Preferences/Network. Not sure where I went wrong here... I installed the V12 package. Any help gratefully requested.

**Comment by adminy** [comment]
Same here, stupid update ... I have a windows partition also and there I get a "could not get device descriptors (code 43)".
Where before the update everything worked great.

**Comment by adminy** [comment]
Managed to roll back, everything works now. Also I have 3 dead ports, they don't seem to come back even with a nvram reset.

**Comment by chris1111** [comment]
> TL-WN722N

I don't know what's wrong here TL-WN722N  suppose to works before and after update 10.15.6 this is already test successfully.
