### ISSUE TITLE
installation failed on 10.15.6

### ISSUE THREAD

**Issue by rforcen** [chris1111/Wireless-USB-Adapter#92]
<img width="732" alt="Screenshot 2020-09-30 at 10 48 39" src="https://user-images.githubusercontent.com/14297391/94663995-9fc55c80-030a-11eb-9d23-7a9d5f2eb66b.png">

**Comment by chris1111** [comment]
Wow great Info thanks!

**Comment by rforcen** [comment]
sorry, my fault i was installing the wrong package
now it's fine, thanks!!
