### ISSUE TITLE
New version of EW-7811Un V2

### ISSUE THREAD

**Issue by ThSGM** [chris1111/Wireless-USB-Adapter#93]
@chris1111 This is not really an issue, but more of a point. The popular EW-7811Un seems to have recently received an update: https://www.edimax.com/edimax/merchandise/merchandise_detail/data/edimax/global/wireless_adapters_n150/ew-7811un_v2/

The only difference I can see on the specs page are slightly higher output powers, Mac OS 10.13 or above required (instead of 10.4+ on the v1), and whatever this is

> One-Click Wireless Connections: Features a software WPS (Wi-Fi Protected Setup) button for easy wireless connections.

Do you have any thoughts on whether to go with the cheaper v1 or the newer v2?

**Comment by chris1111** [comment]
I really don't know sorry. The only thing I know is the driver for the adapter is older the one published here.
