### ISSUE TITLE
not working on RTL8187

### ISSUE THREAD

**Issue by KreatorDev** [chris1111/Wireless-USB-Adapter#94]
please add RTL8187 to be working with your wireless utility app, here's my driver informations from my mac's system report:

Composite Device:
  Product ID:	0x8187
  Vendor ID:	0x0bda  (Realtek Semiconductor Corp.)
  Version:	1.00
  Serial Number:	0025223E159C
  Speed:	Up to 480 Mb/s
  Manufacturer:	Manufacturer_Realtek_RTL8187_
  Location ID:	0x14100000 / 5
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

and thanks for your efforts.

**Comment by chris1111** [comment]
> please add RTL8187 to be working with your wireless utility app, here's my driver informations from my mac's system report:
> 
> Composite Device:
> Product ID: 0x8187
> Vendor ID: 0x0bda (Realtek Semiconductor Corp.)
> Version: 1.00
> Serial Number: 0025223E159C
> Speed: Up to 480 Mb/s
> Manufacturer: Manufacturer_Realtek_RTL8187_
> Location ID: 0x14100000 / 5
> Current Available (mA): 500
> Current Required (mA): 500
> Extra Operating Current (mA): 0
> 
> and thanks for your efforts.


rtl8187 its a old drivers since MacOS 10.5
this drivers is no longer support in macOS for long time
