### ISSUE TITLE
Comfast CF-8811AC with RTL8811CU chipset - is it supported?

### ISSUE THREAD

**Issue by onoakino** [chris1111/Wireless-USB-Adapter#95]
I can see COMFAST CF-811AC on the list of “Known Working and testing adapter”. I found one on aliexpress but the product specs, I see that the chipset it has is RTL8811CU. In your “Support Drivers” list, I can see RTL8811**AU**, but not RTL8811**CU**. I wonder if [Aliexpress COMFAST CF-811AC with a RTL8811CU](https://www.aliexpress.com/item/33000898553.html) chipset is compatible?

**Comment by chris1111** [comment]
Not compatible
