### ISSUE TITLE
Strange issue where certain networks don't work

### ISSUE THREAD

**Issue by ThSGM** [chris1111/Wireless-USB-Adapter#98]
I'm running Opencore macOS Catalina 10.15.7 on a T440P laptop. The Wifi adapter is an Edimax EW-7811Un N150.

![Screen Shot 2020-11-05 at 16 26 45](https://user-images.githubusercontent.com/3396578/99294495-08758380-283c-11eb-8fcf-da3f81f129f0.png)

The weird thing is that it connects to my home network, as well as some other public wifi I have tried. For example like this: 

![Screen Shot 2020-11-16 at 18 47 40](https://user-images.githubusercontent.com/3396578/99294645-3fe43000-283c-11eb-985b-dcc91a1a7637.png)

However, it does not seem to detect any network connection when I am at my place of work (a university). For example, if you are familiar with university networks, it does not detect eduroam. This is despite the fact that it works fine in Windows and every other 'normal' non-Hackintosh laptop detects the necessary network. 

It just scans forever and never picks up the network. I'm totally confused why this might be the case and how I can diagnose it.

**Comment by chris1111** [comment]
I don't know you can google the problem of Edimax adapter
