### ISSUE TITLE
Ethernet Adaptor (en4) instead of Wireless Adapter

### ISSUE THREAD

**Issue by kimromanov** [chris1111/Wireless-USB-Adapter#99]
Hi!
I've installed Wireless USB Adapter-V13 on a MacBook Pro A1297 2011 macOS Catalina 10.15.7 (dosdude1 Patcher) and it determines my USB Wireless Adapter as Ethernet Adaptor (en4), while on macOS Big Sur and using Wireless.USB.Big.Sur.Adapter-V5 is it shown in Network Preferences as ACWirelessAdapter or something like that.
I've bought this USB adapter just for Apple Watch unlock ability. Can You please help me to show it as Wireless adapter for macOS but not Ethernet?

**Comment by chris1111** [comment]
Not possible its the same for all on Catalina
I known strangly on Big Sur release its show ACWirelessAdapter. 
Sorry but this is change from 10.9 I think on older system the USB adapter is show as WIFI
